spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/formationdb
    username: root
    password: admin