spring:
  jpa:
    database: hsql
    database-platform: org.hibernate.dialect.HSQLDialect
    orm: META-INF/orm.xml
    open-in-view: false
  datasource:
    url: jdbc:hsqldb:mem:dataSource
    username: sa
    password: 
    driver-class-name: org.hsqldb.jdbcDriver